[package]
name = "md5sumsum"
version = "0.1.0"
authors = ["Théo Huchard"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
walkdir = "2"
rust-crypto = "0.2.36"